command = "cdl/target/debug/schema-registry"
start-delay = "2s"
# start-after = ["another.toml", "second.toml"]
stdout = "sr.log"
stderr = "sr.log"
user = "$USER"
working-directory = "."

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[failure]
successful-exit-code = [ 0, 1, 255]
strategy = "ignore"

[environment]
keep-env = false
#re-export = [ "PATH", "DB_PASS"]
additional = { INPUT_PORT="6400",DB_NAME="/tmp/sr/db",REPLICATION_ROLE="master",REPLICATION_QUEUE="kafka",KAFKA_BROKERS="localhost:9092",KAFKA_GROUP_ID="sr",REPLICATION_TOPIC_OR_QUEUE="srrepl",REPLICATION_TOPIC_OR_EXCHANGE="srrepl",METRICS_PORT="12501",RUST_LOG = "trace" }

[termination]
signal = "TERM"
wait = "2s"
#die-if-failed  = [ "db.toml"]


