version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "input:1:1,report:1:1,internal:1:1,input:1:1,drin:1:1,csvmin:1:1,cspgin:1:1,errorout:1:1,reportout:1:1,cdlin:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
