command = "cdl/target/debug/data-router"
start-delay = "2s"
# start-after = ["another.toml", "second.toml"]
stdout = "logs/data-router.log"
stderr = "logs/data-router.log"
user = "$USER"
working-directory = "."

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[failure]
successful-exit-code = [ 0, 1, 255]
strategy = "ignore"

[environment]
keep-env = false
#re-export = [ "PATH", "DB_PASS"]

[environment.additional]
COMMUNICATION_METHOD = "kafka"
KAFKA_BROKERS        = "localhost:9092"
KAFKA_GROUP_ID       = "data_router"
INPUT_SOURCE         = "cdl.data.input"
SCHEMA_REGISTRY_ADDR = "http://localhost:50101"
CACHE_CAPACITY       = "1000"
RUST_LOG             = "info,data_router=trace"
OTEL_SERVICE_NAME    = "data-router"
METRICS_PORT         = "0" # Random
STATUS_PORT          = "0" # Random

[termination]
signal = "TERM"
wait = "2s"
#die-if-failed  = [ "db.toml"]
