command = "cdl/target/debug/object-builder"
start-delay = "10s"
start-after = ["schema-registry.toml"]
stdout = "logs/object-builder.log"
stderr = "logs/object-builder.log"
user = "$USER"
working-directory = "."

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[failure]
successful-exit-code = [ 0, 1, 255]
strategy = "ignore"

[environment]
keep-env = false
#re-export = [ "PATH", "DB_PASS"]

[environment.additional]
MQ_METHOD                       = "kafka"
INPUT_PORT                      = "50107"
KAFKA_BROKERS                   = "localhost:9092"
KAFKA_GROUP_ID                  = "object_builder"
MQ_SOURCE                       = "cdl.materialize"
SCHEMA_REGISTRY_ADDR            = "http://localhost:50101"
RUST_LOG                        = "info,object_builder=trace"
OTEL_SERVICE_NAME               = "object-builder"
METRICS_PORT                    = "0" # Random
STATUS_PORT                     = "0" # Random

[termination]
signal = "TERM"
wait = "2s"
#die-if-failed  = [ "db.toml"]
