command = "cdl/target/${TARGET:-debug}/partial-update-engine"
start-delay = "2s"
# start-after = ["another.toml", "second.toml"]
stdout = "logs/partial-update-engine.log"
stderr = "logs/partial-update-engine.log"
user = "$USER"
working-directory = "."

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[failure]
successful-exit-code = [ 0, 1, 255]
strategy = "ignore"

[environment]
keep-env = false
#re-export = [ "PATH", "DB_PASS"]

[environment.additional]
SCHEMA_REGISTRY_ADDR = "http://localhost:50101"
KAFKA_BROKERS        = "localhost:9092"
KAFKA_GROUP_ID       = "partial_update_engine"
NOTIFICATION_TOPIC   = "cdl.reports"
OBJECT_BUILDER_TOPIC = "cdl.materialize"
SLEEP_PHASE_LENGTH   = "1"
RUST_LOG             = "info,partial_update_engine=trace"
OTEL_SERVICE_NAME    = "partial-update-engine"
METRICS_PORT         = "0" # Random
STATUS_PORT          = "0" # Random

[termination]
signal = "TERM"
wait = "2s"
#die-if-failed  = [ "db.toml"]
