command = "cdl/target/debug/query-router"
start-delay = "2s"
# start-after = ["another.toml", "second.toml"]
stdout = "logs/query-router.log"
stderr = "logs/query-router.log"
user = "$USER"
working-directory = "."

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[failure]
successful-exit-code = [ 0, 1, 255]
strategy = "ignore"

[environment]
keep-env = false
#re-export = [ "PATH", "DB_PASS"]

[environment.additional]
CACHE_CAPACITY       = "1024"
INPUT_PORT           = "50103"
SCHEMA_REGISTRY_ADDR = "http://localhost:50101"
RUST_LOG             = "info,query_router=trace"
OTEL_SERVICE_NAME    = "query-router"
METRICS_PORT         = "0" # Random
STATUS_PORT          = "0" # Random

[termination]
signal = "TERM"
wait = "2s"
#die-if-failed  = [ "db.toml"]
