command = "cdl/target/debug/api"
start-delay = "2s"
# start-after = ["another.toml", "second.toml"]
stdout = "logs/api.log"
stderr = "logs/api.log"
user = "$USER"
working-directory = "."

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[failure]
successful-exit-code = [ 0, 1, 255]
strategy = "ignore"

[environment]
keep-env = false
#re-export = [ "PATH", "DB_PASS"]

[environment.additional]
INPUT_PORT                  = "50106"
RUST_LOG                    = "info,api=trace"
SCHEMA_REGISTRY_ADDR        = "http://localhost:50101"
EDGE_REGISTRY_ADDR          = "http://localhost:50110"
ON_DEMAND_MATERIALIZER_ADDR = "http://localhost:50108"
QUERY_ROUTER_ADDR           = "http://localhost:50103"
COMMUNICATION_METHOD        = "kafka"
KAFKA_BROKERS               = "localhost:9093"
KAFKA_GROUP_ID              = "cdl-api"
REPORT_SOURCE               = "cdl.reports"
INSERT_DESTINATION          = "cdl.data.input"
OTEL_SERVICE_NAME           = "api"
METRICS_PORT                = "0" # Random
STATUS_PORT                 = "0" # Random

[termination]
signal = "TERM"
wait = "2s"
#die-if-failed  = [ "db.toml"]
