command = "cdl/target/debug/data-router"
start-delay = "2s"
start-after = ["sr.toml"]
stdout = "dr.log"
stderr = "dr.log"
user = "esavier"
working-directory = "."

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[failure]
successful-exit-code = [ 0, 1, 255]
strategy = "ignore"

[environment]

additional = {KAFKA_TOPIC="input",KAFKA_BROKERS="127.0.0.1:9092",KAFKA_GROUP_ID="dr",KAFKA_ERROR_CHANNEL="errorout",ERROR_TOPIC_OR_EXCHANGE="errorout",INPUT_TOPIC_OR_QUEUE="drin",MESSAGE_QUEUE="kafka",SCHEMA_REGISTRY_ADDR="http://localhost:6400",CACHE_CAPACITY="500",RUST_LOG="trace"}

[termination]
signal = "TERM"
wait = "2s"
#die-if-failed  = [ "db.toml"]

