###
# This is example docker compose that sets up local developer environment.
# Please refer to README.md for instructions on how to run it.
###

version: "2.2"

services:
  druid_command:
    image: cdl-command-service:latest
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        - BIN=command-service
        - ENV=DEV
    command: "/bin/command-service druid"
    environment:
      COMMUNICATION_METHOD: "kafka"
      KAFKA_GROUP_ID: "druid_command"
      KAFKA_BROKERS: "kafka:9093"
      ORDERED_SOURCES: "cdl.timeseries.druid.1.data"
      UNORDERED_SOURCES: "cdl.timeseries.druid.2.data"
      INGESTION_METHOD: KAFKA
      DRUID_OUTPUT_BROKERS: "kafka:9093"
      DRUID_OUTPUT_TOPIC: 'cdl.timeseries.internal.druid'
      REPORT_BROKER: "kafka:9093"
      REPORT_TOPIC: "cdl.reports"
      RUST_LOG: info,command_service=trace
      OTEL_SERVICE_NAME: "druid-command"
      OTEL_EXPORTER_JAEGER_AGENT_HOST: "jaeger"
      OTEL_EXPORTER_JAEGER_AGENT_PORT: "6831"

  druid_query:
    image: cdl-query-service-ts:latest
    command: "/bin/query-service-ts druid"
    ports:
      - "50205:50205"
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        - BIN=query-service-ts
    environment:
      DRUID_QUERY_URL: "http://router:8888/druid/v2"
      DRUID_TABLE_NAME: "cdl.timeseries.internal.druid"
      INPUT_PORT: 50205
      RUST_LOG: debug
      OTEL_SERVICE_NAME: "druid-query"
      OTEL_EXPORTER_JAEGER_AGENT_HOST: "jaeger"
      OTEL_EXPORTER_JAEGER_AGENT_PORT: "6831"

networks:
  compose_default:
    external: true
