###
# This is example docker compose that sets up local developer environment.
# Please refer to README.md for instructions on how to run it.
###

version: "2.2"

services:
  postgres_command:
    image: cdl-command-service:latest
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        - BIN=command-service
        - ENV=DEV
    command: "/bin/command-service postgres"
    environment:
      COMMUNICATION_METHOD: "kafka"
      KAFKA_GROUP_ID: "postgres_command"
      KAFKA_BROKERS: "kafka:9093"
      ORDERED_SOURCES: "cdl.document.1.data"
      UNORDERED_SOURCES: "cdl.document.2.data"
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: postgres
      POSTGRES_SCHEMA: cdl
      REPORT_DESTINATION: "cdl.reports"
      RUST_LOG: info,command_service=trace
      OTEL_SERVICE_NAME: "postgres-command"
      OTEL_EXPORTER_JAEGER_AGENT_HOST: "jaeger"
      OTEL_EXPORTER_JAEGER_AGENT_PORT: "6831"

  postgres_query:
    image: cdl-query-service:latest
    command: "/bin/query-service postgres"
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        - BIN=query-service
        - ENV=DEV
    ports:
      - "50201:50201"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: postgres
      POSTGRES_SCHEMA: cdl
      INPUT_PORT: 50201
      RUST_LOG: info,query_service=trace
      OTEL_SERVICE_NAME: "postgres-query"
      OTEL_EXPORTER_JAEGER_AGENT_HOST: "jaeger"
      OTEL_EXPORTER_JAEGER_AGENT_PORT: "6831"

  postgres_materializer:
    image: cdl-materializer-general:latest
    command: "/bin/materializer-general postgres"
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        - BIN=materializer_general
        - ENV=DEV
    ports:
      - "50203:50203"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: postgres
      POSTGRES_SCHEMA: cdl
      INPUT_PORT: 50203
      RUST_LOG: info,materializer_general=trace
      OTEL_SERVICE_NAME: "postgres-materializer"
      OTEL_EXPORTER_JAEGER_AGENT_HOST: "jaeger"
      OTEL_EXPORTER_JAEGER_AGENT_PORT: "6831"

networks:
  compose_default:
    external: true
