command = "cdl/target/debug/materializer-general postgres"
start-delay = "2s"
# start-after = ["another.toml", "second.toml"]
stdout = "logs/postgres/materializer.log"
stderr = "logs/postgres/materializer.log"
user = "$USER"
working-directory = "."

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[failure]
successful-exit-code = [ 0, 1, 255]
strategy = "ignore"

[environment]
keep-env = false
#re-export = [ "PATH", "DB_PASS"]

[environment.additional]
POSTGRES_USERNAME = "postgres"
POSTGRES_PASSWORD = "1234"
POSTGRES_HOST     = "localhost"
POSTGRES_PORT     = "5432"
POSTGRES_DBNAME   = "postgres"
POSTGRES_SCHEMA   = "cdl"
INPUT_PORT        = "50203"
RUST_LOG          = "info,materializer_general=trace"
OTEL_SERVICE_NAME = "postgres-materializer"
METRICS_PORT      = "0" # Random
STATUS_PORT       = "0" # Random

[termination]
signal = "TERM"
wait = "2s"
#die-if-failed  = [ "db.toml"]
