command = "cdl/target/${TARGET:-debug}/query-service-ts victoria"
start-delay = "2s"
# start-after = ["another.toml", "second.toml"]
stdout = "logs/victoria-metrics/query-service.log"
stderr = "logs/victoria-metrics/query-service.log"
user = "$USER"
working-directory = "."

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[failure]
successful-exit-code = [ 0, 1, 255]
strategy = "ignore"

[environment]
keep-env = false
#re-export = [ "PATH", "DB_PASS"]

[environment.additional]
INPUT_PORT         = "50203"
VICTORIA_QUERY_URL = "http://localhost:8428/api/v1"
RUST_LOG           = "info,query_service=trace"
OTEL_SERVICE_NAME  = "victoria-metrics-query"
METRICS_PORT       = "0" # Random
STATUS_PORT        = "0" # Random

[termination]
signal = "TERM"
wait = "2s"
#die-if-failed  = [ "db.toml"]
