command = "cdl/target/${TARGET:-debug}/command-service druid"
start-delay = "2s"
# start-after = ["another.toml", "second.toml"]
stdout = "logs/druid/command-service.log"
stderr = "logs/druid/command-service.log"
user = "$USER"
working-directory = "."

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[failure]
successful-exit-code = [ 0, 1, 255]
strategy = "ignore"

[environment]
keep-env = false
#re-export = [ "PATH", "DB_PASS"]

[environment.additional]
COMMUNICATION_METHOD        = "kafka"
KAFKA_GROUP_ID              = "druid_command"
KAFKA_BROKERS               = "localhost:9092"
ORDERED_SOURCES             = "cdl.timeseries.druid.1.data"
UNORDERED_SOURCES           = "cdl.timeseries.druid.2.data"
DRUID_OUTPUT_BROKERS        = "localhost:9092"
DRUID_OUTPUT_TOPIC          = "cdl.timeseries.internal.druid"
REPORT_DESTINATION          = "cdl.reports"
RUST_LOG                    = "info,command_service=trace"
OTEL_SERVICE_NAME           = "druid-command"
METRICS_PORT                = "0" # Random
STATUS_PORT                 = "0" # Random

[termination]
signal = "TERM"
wait = "2s"
#die-if-failed  = [ "db.toml"]
